// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7cdZ2-SVTVSjdsaSqNstRXn87tR0CAqA',
    appId: '1:448811679409:web:acda9bfd034f2f14aeec90',
    messagingSenderId: '448811679409',
    projectId: 'green-egypt-f80b9',
    authDomain: 'green-egypt-f80b9.firebaseapp.com',
    storageBucket: 'green-egypt-f80b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuzui1J-zbTgMbiwoUAnNB5bG6RfEyENs',
    appId: '1:448811679409:android:3c0985348c7ea715aeec90',
    messagingSenderId: '448811679409',
    projectId: 'green-egypt-f80b9',
    storageBucket: 'green-egypt-f80b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4jlld_8EOpru3ynQIpmAQltlsNkAisxY',
    appId: '1:448811679409:ios:f792a5b2035eb362aeec90',
    messagingSenderId: '448811679409',
    projectId: 'green-egypt-f80b9',
    storageBucket: 'green-egypt-f80b9.appspot.com',
    androidClientId: '448811679409-op22jdur6are3b4hvdfc16dvet4mnfoo.apps.googleusercontent.com',
    iosClientId: '448811679409-ge4p8hp974b5lilv4o9fiq1dh1t3t09u.apps.googleusercontent.com',
    iosBundleId: 'tech.mavica.greenEgypt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4jlld_8EOpru3ynQIpmAQltlsNkAisxY',
    appId: '1:448811679409:ios:f792a5b2035eb362aeec90',
    messagingSenderId: '448811679409',
    projectId: 'green-egypt-f80b9',
    storageBucket: 'green-egypt-f80b9.appspot.com',
    androidClientId: '448811679409-op22jdur6are3b4hvdfc16dvet4mnfoo.apps.googleusercontent.com',
    iosClientId: '448811679409-ge4p8hp974b5lilv4o9fiq1dh1t3t09u.apps.googleusercontent.com',
    iosBundleId: 'tech.mavica.greenEgypt',
  );
}
